services:
  healthcheck-bot:
    build: .
    container_name: healthcheck
    restart: always
    ports:
      - "8090:8080"
    environment:
      - BOT_USERNAME=
      - BOT_TOKEN=
      - FRONTEND_URL=
      - BACKEND_URL=
      - TELEGRAM_ID=
      - HEALTHCHECK_RATE=
    volumes:
      - ./logs:/var/logs
    command: java -XX:+UseG1GC -jar /app/target/healthcheck.jar
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge